openapi: '3.0.2'

info:
  title: Shiika
  description: |
    This is siika
  version: 2.1.5

servers:
  - url: http://siika
    description: for production

tags:
  - name: login
    description: for login and register
  - name: kaminoku
    description: related to kaminoku
  - name: simonoku(tanka)
    description: related to simonoku
  - name: user
    description: related to user

paths:
  /login:
    post:
      tags:
        - login
      operationId: postLogin
      summary: send user name and password for login
      description: send user name and password for login
      requestBody:
        $ref: '#/components/requestBodies/Login'
      responses:
        '201':
          $ref: '#/components/responses/Nocontent'
        '400':
          description: Bad Request

  /register:
    post:
      tags:
        - login
      operationId: postRegister
      summary: send user name and password for sign up 
      description: send user name and password for sign up 
      requestBody:
        $ref: '#/components/requestBodies/Login'
      responses:
        '201':
          $ref: '#/components/responses/Nocontent'
        '400':
          description: Bad Request
          
  /kaminoku:
    get:
      tags:
        - kaminoku
      operationId: getKaminoku
      summary: get random kaminokus
      description: get kaminoku array
      responses:
        '200':
          $ref: '#/components/responses/kaminokus'
    post:
      tags:
        - kaminoku
      operationId: postKaminoku
      summary: send kaminoku content
      description: send kaminoku content
      requestBody:
        $ref: '#/components/requestBodies/kaminoku'
      responses:
        '201':
          $ref: '#/components/responses/Nocontent'
        '401':
          description: Unorthorized  
          
      
  /kaminoku/{kaminoku_id}:
    parameters:
      - $ref: '#/components/parameters/kaminoku_id'
    get:
      tags:
        - kaminoku
      operationId: getKaminokuDetail
      summary: get a kaminoku by id
      description: get a kaminoku by id
      responses:
        '200':
          $ref: '#/components/responses/kaminoku'
        '400':
          description: Bad Request
          
          
  /kaminoku/{kaminoku_id}/simonoku:
    parameters:
      - $ref: '#/components/parameters/kaminoku_id'
    get:
      tags:
        - simonoku(tanka)
      responses:
        '200':
          $ref: '#/components/responses/tankas'
    post:
      tags:
        - simonoku(tanka)
      requestBody:
        $ref: '#/components/requestBodies/simonoku'
      responses:
        '201':
          $ref: '#/components/responses/Nocontent'
        '401':
          description: Unorthorized
          
  /simonoku:
    get:
      tags:
        - simonoku(tanka)
      responses:
        '200':
          $ref: '#/components/responses/tankas'
  /user/{user_id}/kaminoku:
    parameters:
      - $ref: '#/components/parameters/user_id'
    get:
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/kaminokus'
  /user/{user_id}/simonoku:
    parameters:
      - $ref: '#/components/parameters/user_id'
    get:
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/tankas'
    
      
components:
  schemas:
    Login:
      type: object
      required:
        - userid
        - password
      properties:
        userid:
          type: string
        password:
          type: string
          
    RequestKaminoku:
      type: object
      required:
        - content
      properties:
        content:
          $ref: '#/components/schemas/Fsf'
          
    Kaminoku:
      type: object
      required:
        - id
        - content
        - userid
      properties:
        id:
          type: string
          format: uuid
        content:
          $ref: '#/components/schemas/Fsf'
        userid:
          type: string

    Simonoku:
      type: object
      required:
        - id
        - content
        - userid
      properties:
        id:
          type: string
          format: uuid
        content:
          $ref: '#/components/schemas/Ss'
        userid:
          type: string
          
    RequestSimonoku:
      type: object
      required:
        - content
      properties:
        content:
          $ref: '#/components/schemas/Ss'
  
    Tanka:
      type: object
      required:
        - kaminoku
        - simonoku
      properties:
        kaminoku:
          $ref: '#/components/schemas/Kaminoku'
        simonoku:
          $ref: '#/components/schemas/Simonoku'

    Fsf:
      type: object
      required:
        - first
        - second
        - third
      properties:
        first:
          type: string
        second:
          type: string
        third:
          type: string
    Ss:
      type: object
      required:
        - fourth
        - fifth
      properties:
        fourth:
          type: string
        fifth:
          type: string
        
  requestBodies:
    Login:
      description: for login
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
            
    kaminoku:
      description: post kaminoku
      required: true
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/RequestKaminoku'
            
    simonoku:
      description: post simonoku
      required: true
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/RequestSimonoku'

  responses:
    Nocontent:
      description: Nocontent

    kaminokus:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Kaminoku'
              
    kaminoku:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Kaminoku'

    tankas:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tanka'
              
    tanka:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tanka'
  
  parameters:
    session:
      name: session
      in: cookie
      required: true
      schema:
        type: string
        
    kaminoku_id:
      name: kaminoku_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
        
    user_id:
      name: user_id
      in: path
      required: true
      schema:
        type: string
        
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
